=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/book.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://books"
	targetNamespace="http://books" elementFormDefault="qualified">
  <xsd:element name="bookList">
  	<xsd:complexType>
  		<xsd:sequence>
  			<xsd:element maxOccurs="unbounded" ref="book"/>  		
  		</xsd:sequence>  	
  	</xsd:complexType>  
  </xsd:element>
  <xsd:element name="book">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="title"/>
      <xsd:choice>
         <xsd:element ref="author"/>
         <xsd:element ref="editor"/>
      </xsd:choice>
      <xsd:element ref="ISBN"/>
      <xsd:element minOccurs="0" name="edition" type="Edition"/>
      <xsd:element ref="publisher"/>
      <xsd:element minOccurs="0" ref="year"/>
    </xsd:sequence>
    <xsd:attribute name="price" type="xsd:decimal"/>
    <xsd:attribute name="inStock" use="required">
       <xsd:simpleType>
          <xsd:restriction base="xsd:string">
              <xsd:enumeration value="Yes"/>
              <xsd:enumeration value="No"/>
          </xsd:restriction>
       </xsd:simpleType>
    </xsd:attribute>
  </xsd:complexType>
  </xsd:element>

  <xsd:element name="title" type="xsd:string"/>
  
  <xsd:element name="author">
     <xsd:complexType mixed="true">
     	<xsd:sequence>
     			<xsd:element name="name" type="xsd:string"/>
     			<xsd:element name="lastName" type="xsd:string"/>   		
     	</xsd:sequence>     
     </xsd:complexType>
  </xsd:element>
  <xsd:element name="ISBN" type="xsd:string"/>
  
  <xsd:element name="publisher" type="xsd:string"/>
  <xsd:element name="editor" type="xsd:string"/>
  <xsd:element name="year">
     <xsd:simpleType>
        <xsd:restriction base="xsd:string">
          <xsd:pattern value="[0-9]{4}"/>
        </xsd:restriction>
     </xsd:simpleType>
  </xsd:element>
  
  <xsd:simpleType name="Edition">
     <xsd:restriction base="xsd:string">
        <xsd:enumeration value="First"/>
        <xsd:enumeration value="Second"/>
        <xsd:enumeration value="Third"/>
        <xsd:enumeration value="Fourth"/>
        <xsd:enumeration value="Fifth"/>
     </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/joinpointWeavingTest/result.xml
<?xml version="1.0" encoding="UTF-8"?><bookList xmlns="http://books" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://books book.xsd">
  <books:book xmlns:books="http://books" xmlns="http://www.hyperadapt.net/pxweave/aspects" inStock="No" price="16.95"><books:title>Under The Dome: A Novel</books:title><books:author><books:name>Stephen</books:name><books:lastName>King</books:lastName></books:author><books:ISBN>0340992565</books:ISBN><books:edition>First</books:edition><books:publisher>Hodder and Stoughton</books:publisher></books:book><books:book xmlns:books="http://books" xmlns="http://www.hyperadapt.net/pxweave/aspects" inStock="Yes" price="15.95"><books:title>Full Dark, No Stars</books:title><books:author><books:name>Stephen</books:name><books:lastName>King</books:lastName></books:author><books:ISBN>1444712543</books:ISBN><books:edition>First</books:edition><books:publisher>Hodder and Stoughton</books:publisher></books:book><book inStock="Yes" price="64.14">
  	<title>Principles: How they got lost.</title>
	<author>  
		<name>Sam</name>
			<lastName>Freek</lastName>
	</author>
	<ISBN>0-201-12188-6</ISBN>
	<edition>Second</edition>
	<publisher>VVM</publisher>
  </book>
  <book inStock="Yes" price="39.22">
	<title>The Moon Story</title>
	<author><name>M.</name>	
		<lastName>Rainsburg</lastName>
	</author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  <book inStock="No" price="44.98">
	<title>Some Title</title> 
	<author>mixedContent<name>A</name><lastName>Name</lastName></author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  </bookList>

=== javafrog/hyperadapt/net.hyperadapt.pxweave.test/testData/result.xml
<?xml version="1.0" encoding="UTF-8"?><bookList xmlns="http://books" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://books book.xsd">
  <book inStock="Yes" price="64.14">
  	<title><img>Principles: How they got lost.-cover.jpg</img></title>
	<author>  
		<name>Sam</name>
			<lastName>Freek</lastName>
	</author>
	<ISBN>0-201-12188-6</ISBN>
	<edition>Second</edition>
	<publisher>VVM</publisher>
  </book>
  <book inStock="Yes" price="39.22">
	<title><img>The Moon Story-cover.jpg</img></title>
	<author><name>M.</name>	
		<lastName>Rainsburg</lastName>
	</author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  <book inStock="No" price="44.98">
	<title><img>Some Title-cover.jpg</img></title> 
	<author>mixedContent<name>A</name><lastName>Name</lastName></author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  </bookList>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.test/testData/book.xml
<?xml version="1.0"?>
<bookList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://books book.xsd"
xmlns="http://books">
  <book inStock="Yes" price="64.14">
  	<title>Principles: How they got lost.</title>
	<author>  
		<name>Sam</name>
			<lastName>Freek</lastName>
	</author>
	<ISBN>0-201-12188-6</ISBN>
	<edition>Second</edition>
	<publisher>VVM</publisher>
  </book>
  <book inStock="Yes" price="39.22">
	<title>The Moon Story</title>
	<author><name>M.</name>	
		<lastName>Rainsburg</lastName>
	</author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  <book inStock="No" price="44.98">
	<title>Some Title</title> 
	<author>mixedContent<name>A</name><lastName>Name</lastName></author>
	<ISBN>0-251-16135-2</ISBN>
	<edition>Second</edition>
	<publisher>RS Media</publisher>
  </book>
  </bookList>
