=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave/schemas/weaverConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.hyperadapt.net/pxweave/config" 
		xmlns:tns="http://www.hyperadapt.net/pxweave/config"
		elementFormDefault="qualified">
<element name="weaverConfiguration">
	<complexType>
		<sequence>
			<element name="aspectFiles" type="tns:AspectFiles"/>	
			<element name="namespaces" type="tns:Namespaces" minOccurs="0"/>
			<element name="validationMode" type="tns:ValidationType"/>
		</sequence>
		<attribute name="reportInteractions" use="optional" type="boolean"/>
	</complexType>
</element>

<complexType name="AspectFiles">
	<sequence>
		<element name="aspectFile" type="string" minOccurs="1" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<simpleType name="OperationValidation">
	<restriction base="string">
		<enumeration value="none"/>
		<enumeration value="DOML3"/>
		<enumeration value="DOML3Validation"/>
	</restriction>
</simpleType>

<complexType name="Namespaces">
	<sequence>
		<element name="namespace" type="tns:NamespaceDeclaration" minOccurs="1" maxOccurs="unbounded"/>
	</sequence>
</complexType>

<complexType name="NamespaceDeclaration">
	<attribute name="prefix" use="required" type="string"/>
	<attribute name="name" use="required" type="anyURI"/>
	<attribute name="definition" use="optional" type="anyURI"/>
</complexType>

<complexType name="ValidationType">
	<simpleContent>	
		<extension base="tns:OperationValidation">
			<attribute name="validateBeforeWeaving" type="boolean" default="false"/>	
			<attribute name="validateAfterWeaving" type="boolean" default="false"/>	
		</extension>		
	</simpleContent>
</complexType>
</schema>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.test/testData/interactionDetectionTest/weaverConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<weaverConfiguration
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/config schemas/weaverConfig.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/config"
	reportInteractions="true">
	<aspectFiles>
		<!-- aspectFile>DeviceIndependence.xml</aspectFile-->
		<aspectFile>InsertSomething.xml</aspectFile>
		<aspectFile>Translation.xml</aspectFile>
	</aspectFiles>
	<namespaces>
		<namespace prefix="aco" name="http://www.hyperadapt.net/amacont/2008/AmaComponent" definition="http://www.hyperadapt.net/amacont/2008/AmaComponent.xsd"/>  
		<namespace prefix="amet" name="http://www.hyperadapt.net/amacont/2008/AmaMetaInformation" definition="http://www.hyperadapt.net/amacont/2008/AmaMetaInformation.xsd"/>  
		<namespace prefix="alay" name="http://www.hyperadapt.net/amacont/2008/AmaLayout" definition="http://www.hyperadapt.net/amacont/2008/AmaLayout.xsd"/>  
		<namespace prefix="aada" name="http://www.hyperadapt.net/amacont/2008/AmaAdaptation" definition="http://www.hyperadapt.net/amacont/2008/AmaAdaptation.xsd"/>  
		<namespace prefix="asem" name="http://www.hyperadapt.net/amacont/2008/AmaSemantics" definition="http://www.hyperadapt.net/amacont/2008/AmaSemantics.xsd"/>  
		<namespace prefix="mpeg7" name="http://www.mpeg7.org/2001/MPEG-7_Schema" definition="http://www.mpeg7.org/2001/MPEG-7_Schema/mpeg7-v1.xsd"/>  
	</namespaces>
	<validationMode>none</validationMode>
</weaverConfiguration>
