=== javafrog/hyperadapt/net.hyperadapt.pxweave/schemas/aspectE2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hyperadapt.net/pxweave/aspects" xmlns:tns="http://www.hyperadapt.net/pxweave/aspects" elementFormDefault="qualified">

	<element name="aspect" type="tns:Aspect" />
	<complexType name="Aspect">
		<sequence>
			<element name="interface" type="tns:Interface" />
			<element name="adviceGroup" minOccurs="1" maxOccurs="unbounded" type="tns:AdviceGroup">
				<annotation>
					<documentation xml:lang="de">gruppiert Advices, die zum gleichen Scope und Kontext gehören</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string">
			<annotation>
				<documentation xml:lang="de">Name des Aspekts</documentation>
			</annotation>
		</attribute>
	</complexType>


	<complexType name="AdviceGroup">
		<sequence>
			<element name="depends" minOccurs="0" maxOccurs="1" type="tns:Dependency">
				<annotation>
					<documentation xml:lang="de">Evaluierung von Kontextvariablen um Gültigkeit der AdviceGroup festzulegen, Variablen über X-Path binden, boolscher Ausdruck</documentation>
				</annotation>
			</element>
			<element name="scope" minOccurs="1" maxOccurs="1" type="tns:Scope">
				<annotation>
					<documentation xml:lang="de">Gültigkeitsbereich der Advices</documentation>
				</annotation>
			</element>
			<element name="advices" type="tns:Advice" />
		</sequence>
	</complexType>

	<complexType name="Advice">
		<choice minOccurs="1" maxOccurs="unbounded">
			<annotation>
				<documentation xml:lang="de">1-n Advices; alle Advices müssen zumindest einen Joinpoint auswählen</documentation>
			</annotation>
			<element name="chooseVariant" type="tns:ChooseVariant">
				<annotation>
					<documentation xml:lang="de">Variantenauswahl: in n ElementNodes kann ein elementwertiger Kindknoten (joinPoint zeigt auf kindknoten) gewählt werden, die restlichen Kindknoten der ElementNodes werden entfernt, sofern sie gneauso heißen wie der joinpoint.</documentation>
				</annotation>
			</element>
			<element name="changeOrder" type="tns:ChangeOrder">
				<annotation>
					<documentation xml:lang="de">Reihenfolge von KindKnoten (inkl.TextNodes) von n ElementNodes ändern</documentation>
				</annotation>
			</element>
			<element name="changeValue" type="tns:ChangeValue">
				<annotation>
					<documentation xml:lang="de">wählt n ElementNodes oder AttributeNodes aus, ersetzt alle textNodes (ergebnis ist immer genau ein textNode/joinPoint) im ElementNode durch den evaluierten Wert bzw. ersetzt alle AttributeValues durch den gegebenen Wert</documentation>
				</annotation>
			</element>
			<element name="enrichContent" type="tns:EnrichContent">
				<annotation>
					<documentation xml:lang="de">fügt in n ElementNodes einen textNode an gewählter position ein</documentation>
				</annotation>
			</element>
			<element name="reduceContent" type="tns:ReduceContent">
				<annotation>
					<documentation xml:lang="de">wählt n ElementNodes aus, enfernt alle textNodes oder den text aus allen textNodes, der in deletePart angegeben ist </documentation>
				</annotation>
			</element>
			<element name="collapseElement" type="tns:CollapseElement">
				<annotation>
					<documentation xml:lang="de">ersetzt in n elementNodes alle kindKnoten durch einen textNode</documentation>
				</annotation>
			</element>
			<element name="expandElement" type="tns:ExpandElement">
				<annotation>
					<documentation xml:lang="de">ersetzt in n elementNodes die textNodes durch elementNode, dh. löscht alle textNodes, ersetzt sie durch einen elementNode</documentation>
				</annotation>
			</element>
			<element name="insertElement" type="tns:InsertElement">
				<annotation>
					<documentation xml:lang="de">Fügt in n ElementNodes ein generierten ElementNode an der gewählten Position als KindKnoten ein, der JoinPoint ist über $joinPoint im elementTemplate verfügbar - für jeden JoinPoint kann ein spezifisches Element generiert werden</documentation>
				</annotation>
			</element>
			<element name="moveElement" type="tns:MoveElement">
				<annotation>
					<documentation xml:lang="de">genau einen ElementNode auschneiden und als Kindelement eines ElementKnotens wieder einfügen, Ziel muss nicht im scope liegen, Quelle darf im Ziel nicht enthalten sein, Quelle und Ziel müssen unterschiedlich sein, Position des Neuen Kindknotens wird über Attribut Position (0.-n.pos) bestimmt->anhängen falls negativ</documentation>
				</annotation>
			</element>
			<element name="delete" type="tns:Delete">
				<annotation>
					<documentation xml:lang="de">n AttributeNodes, ElementNodes oder TextNodes entfernen</documentation>
				</annotation>
			</element>
			<element name="fillComponentById" type="tns:FillComponentByID">
				<annotation>
					<documentation xml:lang="de">fügt in die gewählten joinPoints die Kinder aus einem korrespondierendem source node. der source node wird anhand eines joinPoin-attributs targetID und eines source node attributs sourceID gefunden. joinPoint und source müssen elementNodes sein, für jeden joinPoint muss es genau einen source node geben</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>

	<!--******************************************* abstrakte Advices ********************************************** -->


	<complexType name="BasicAdvice" abstract="true">
		<annotation>
			<documentation xml:lang="de">Advice ohne "Value"-Angaben, nur Löschen/Sortieren/Auswählen von Content</documentation>
		</annotation>
		<sequence>
			<element name="pointcut" type="tns:XPath" />
		</sequence>
	</complexType>

	<complexType name="SimpleAdvice" abstract="true">
		<annotation>
			<documentation xml:lang="de">SimpleValue erlaubt das Erzeugen von textContent</documentation>
		</annotation>
		<complexContent>
			<extension base="tns:BasicAdvice">
				<sequence>
					<element name="value" type="tns:SimpleValue" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ComplexAdvice" abstract="true">
		<annotation>
			<documentation xml:lang="de">ComplexValue erlaubt das Erzeugen eines elementNodes</documentation>
		</annotation>
		<complexContent>
			<extension base="tns:BasicAdvice">
				<sequence>
					<element name="value" type="tns:ComplexValue" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>


	<!--******************************************** konkrete Advices *********************************************** -->
	<complexType name="FillComponentByID">
		<complexContent>
			<extension base="tns:BasicAdvice">
				<sequence>
					<group ref="tns:componentGroup" />
					<element name="source" type="tns:SourceContainer" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<group name="componentGroup">
		<sequence>
			<element name="identifyingAttribute" type="string" />
		</sequence>
	</group>

	<complexType name="SourceContainer">
		<sequence>
			<element name="sourceComponents" type="tns:XPath" />
			<group ref="tns:componentGroup" />
		</sequence>
		<attribute name="document" type="tns:Name" />
	</complexType>

	<complexType name="ChangeOrder">
		<complexContent>
			<extension base="tns:BasicAdvice">
				<choice>
					<element name="sortByName">
						<annotation>
							<documentation xml:lang="de">by attr</documentation>
						</annotation>
					</element>
					<element name="reverseOrder" />
					<element name="permutation" type="tns:Permutation">
						<annotation>
							<documentation xml:lang="de">Permutation gibt neue Reihenfolge der Elemente an</documentation>
						</annotation>
					</element>
				</choice>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ChooseVariant">
		<complexContent>
			<extension base="tns:BasicAdvice" />
		</complexContent>
	</complexType>

	<complexType name="Delete">
		<complexContent>
			<extension base="tns:BasicAdvice" />
		</complexContent>
	</complexType>

	<complexType name="ReduceContent">
		<complexContent>
			<extension base="tns:BasicAdvice">
				<attribute name="deletePart" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ChangeValue">
		<complexContent>
			<extension base="tns:SimpleAdvice" />
		</complexContent>
	</complexType>

	<complexType name="EnrichContent">
		<complexContent>
			<extension base="tns:SimpleAdvice">
				<attribute name="position" type="integer" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="CollapseElement">
		<complexContent>
			<extension base="tns:SimpleAdvice" />
		</complexContent>
	</complexType>


	<complexType name="ExpandElement">
		<complexContent>
			<extension base="tns:ComplexAdvice" />
		</complexContent>
	</complexType>

	<complexType name="InsertElement">
		<complexContent>
			<extension base="tns:ComplexAdvice">
				<attribute name="position" type="integer" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="MoveElement">
		<complexContent>
			<extension base="tns:BasicAdvice">
				<sequence>
					<element name="to" type="tns:XPath" />
				</sequence>
				<attribute name="position" type="integer" use="required" />
			</extension>
		</complexContent>
	</complexType>



	<!--******************************************** sonstiges *************************************************** -->
	<complexType name="Interface">
		<sequence>
			<element name="core" type="tns:Parameter">
				<annotation>
					<documentation xml:lang="de">ID und Typ (XSD) des Core-Dokuments</documentation>
				</annotation>
			</element>
			<element name="contextParameters" minOccurs="0" maxOccurs="1" type="tns:ContextVarDecl" />
			<element name="documentParameters" minOccurs="0" maxOccurs="1" type="tns:DocumentParameterDecl" />
			<element name="aspectOrder" type="tns:AspectOrder" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="Scope">
		<sequence>
			<element name="xpath" type="tns:XPath" minOccurs="0" maxOccurs="unbounded" />
			<element name="joinpoint" type="tns:ProgrammaticScope" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="AspectOrder">
		<sequence>
			<element name="afterAspect" type="string" minOccurs="0" maxOccurs="unbounded" />
			<element name="beforeAspect" type="string" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="absolutePosition" type="tns:AbsolutePosition" default="none" />
	</complexType>

	<simpleType name="AbsolutePosition">
		<restriction base="string">
			<enumeration value="asFirst" />
			<enumeration value="asLast" />
			<enumeration value="none" />
		</restriction>
	</simpleType>

	<simpleType name="AdviceLocator">
		<restriction base="string">
			<enumeration value="before" />
			<enumeration value="after" />
		</restriction>
	</simpleType>

	<complexType name="XPath">
		<simpleContent>
			<extension base="string">
				<!-- <attribute name="type" type="tns:TypeDef" use="required"/> -->
				<attribute name="root" type="string" />
			</extension>
		</simpleContent>
	</complexType>

	<!-- inserted by skarol -->
	<complexType name="ProgrammaticScope" abstract="false">
		<attribute name="name" type="string" />
		<attribute name="locator" type="tns:AdviceLocator" />
	</complexType>

	<simpleType name="Permutation">
		<restriction base="string">
			<!--Tupelschreibweise der Permutation: (1 4 3 2 5) -->
			<pattern value="\(([1-9][0-9]*\s)+(([1-9][0-9]*))+\)" />
		</restriction>

	</simpleType>

	<complexType name="Parameter">
		<attribute name="id" type="string" use="required" />
		<attribute name="type" type="string" use="required" />
	</complexType>

	<complexType name="Dependency">
		<sequence>
			<element name="boolExpr" type="string">
				<annotation>
					<documentation xml:lang="de">boolscher Ausdruck über ausgewählte Parameter</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="SimpleValue">
		<annotation>
			<documentation xml:lang="de">für konkrete Avices, die nur textwertige Änderungen vornehmen</documentation>
		</annotation>
		<sequence>
			<element name="varDecl" type="tns:VarDecl" minOccurs="0" />
			<element name="textTemplate" type="tns:TextTemplate" />
		</sequence>
	</complexType>

	<complexType name="ComplexValue">
		<annotation>
			<documentation xml:lang="de">für konkrete Avices, die ein Element erzeugen müssen</documentation>
		</annotation>
		<sequence>
			<element name="varDecl" type="tns:VarDecl" minOccurs="0" />
			<element name="elementTemplate" type="tns:ElementTemplate" />
		</sequence>
	</complexType>

	<complexType name="TextTemplate">
		<simpleContent>
			<extension base="string" />
		</simpleContent>
	</complexType>

	<complexType name="ElementTemplate" mixed="true">
		<sequence minOccurs="1" maxOccurs="1">
			<any processContents="skip" />
		</sequence>
	</complexType>

	<complexType name="VarDecl">
		<sequence>
			<element name="var" maxOccurs="unbounded" type="tns:Var" />
		</sequence>
	</complexType>

	<complexType name="ContextVarDecl">
		<sequence>
			<element name="parameter" minOccurs="1" maxOccurs="unbounded" type="tns:ContextParameter" />
		</sequence>
	</complexType>

	<complexType name="DocumentParameterDecl">
		<sequence>
			<element name="documentParameter" maxOccurs="unbounded" type="tns:DocumentParameter" />
		</sequence>
	</complexType>

	<complexType name="ContextParameter">
		<sequence>
			<element name="name" type="tns:Name" />
		</sequence>
		<!--<attribute name="type" type="tns:TypeDefContextParam" use="required"/> -->
	</complexType>

	<complexType name="DocumentParameter">
		<sequence>
			<element name="name" type="tns:Name" />
			<element name="uri" type="anyURI" />
		</sequence>
	</complexType>

	<complexType name="Var">
		<sequence>
			<element name="name" type="tns:Name" />
			<element name="xpath" type="tns:XPath" />
		</sequence>
		<!-- <attribute name="type" type="tns:TypeDef" use="required"/> -->
	</complexType>

	<simpleType name="TypeDef">
		<restriction base="string">
			<enumeration value="integer" />
			<enumeration value="double" />
			<enumeration value="float" />
			<enumeration value="short" />
			<enumeration value="string" />
			<enumeration value="boolean" />
			<enumeration value="elementNode" />
		</restriction>
	</simpleType>

	<simpleType name="TypeDefContextParam">
		<restriction base="string">
			<enumeration value="integer" />
			<enumeration value="double" />
			<enumeration value="float" />
			<enumeration value="short" />
			<enumeration value="string" />
			<enumeration value="boolean" />
		</restriction>
	</simpleType>

	<simpleType name="Name">
		<restriction base="string">
			<pattern value="[a-zA-Z]\w*" />
		</restriction>
	</simpleType>

</schema>

=== javafrog/hyperadapt/net.hyperadapt.pxweave.test/testData/weavingOperationsTest/AspectReduceContent.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="reduceContent"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://books" />
	</interface>
	<adviceGroup>
		<scope>
			<xpath>/books:bookList</xpath>
		</scope>
		<advices>
			<reduceContent>
				<pointcut>books:book/books:author</pointcut>
			</reduceContent>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/weavingOperationsTest/AspectChangeValue.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="aspectChangeValue"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://books" />
	</interface>
	<adviceGroup>
		<scope>
			<xpath>/books:bookList</xpath>
		</scope>
		<advices>
			<changeValue>
				<pointcut>/books:book/attribute::price</pointcut>
				<value>
					<textTemplate>$joinPoint*2</textTemplate>
				</value>
			</changeValue>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/interactionDetectionTest/InsertSomething.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="InsertSomething"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aco="http://www.hyperadapt.net/amacont/2008/AmaComponent"
	xmlns:amet="http://www.hyperadapt.net/amacont/2008/AmaMetaInformation"
	xmlns:alay="http://www.hyperadapt.net/amacont/2008/AmaLayout" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://www.hyperadapt.net/amacont/2008/AmaComponent" />
	</interface>
	<!-- adviceGroup> <scope> <xpath>//aco:AmaSetComponent[@id='a56zuaa!no']</xpath> 
		<joinpoint locator="before" name="T_WebService"/> </scope> <advices> <changeValue> 
		<pointcut>@query</pointcut> <value> <textTemplate>'select interpret.name 
		AS interpret,interpret.id AS id,ceil(count(album.interpret_id)/4) AS amount 
		from interpret inner join album on interpret.id=album.interpret_id group 
		by interpret.id order by interpret.name'</textTemplate> </value> </changeValue> 
		<delete> <pointcut>/aco:AmaListComponent[@name='interpret_row_title_img']</pointcut> 
		</delete> <delete> <pointcut>/alay:ComponentRef[child::text()='interpret_row_title_img']</pointcut> 
		</delete> </advices> </adviceGroup -->
	<!-- adviceGroup> <scope> <xpath>//aco:AmaSetComponent[@id='l84y6kh0']/aco:SubComponents</xpath> 
		<joinpoint locator="after" name="T_WebService" /> </scope> <advices> <insertElement 
		position="1"> <pointcut>/aco:AmaAccessElement</pointcut> <value> <elementTemplate> 
		<aco:Hyperlinks> <aco:AmaComponentLinkComponent name="h1" layer="Hyperlink"> 
		<aco:MetaInformation> <amet:LinkComponentMetaData> <amet:linktype>Navigationslink</amet:linktype> 
		</amet:LinkComponentMetaData> </aco:MetaInformation> <aco:From component="logo_img_smaller" 
		/> <aco:To base="album.ama" /> </aco:AmaComponentLinkComponent> </aco:Hyperlinks> 
		</elementTemplate> </value> </insertElement> <insertElement position="1"> 
		<pointcut>/aco:AmaAccessElement</pointcut> <value> <elementTemplate> <aco:SubComponents> 
		<aco:AmaImageComponent id="m30b997s" layer="Media" name="logo_img_smaller"> 
		<aco:MetaInformation> <amet:ImageMetaData> <amet:source>images/logo_small.png</amet:source> 
		<amet:alt>SoundNexus smaller Logo</amet:alt> </amet:ImageMetaData> </aco:MetaInformation> 
		</aco:AmaImageComponent> </aco:SubComponents> </elementTemplate> </value> 
		</insertElement> </advices> </adviceGroup -->

	<!--adviceGroup> <depends> <boolExpr>0 = 0</boolExpr> </depends> <scope> 
		<xpath>//aco:AmaSetComponent[@id='j91t3sk7']/aco:SubComponents/aco:AmaAccessElement 
		</xpath> <joinpoint locator="after" name="T_WebService" /> </scope> <advices> 
		<moveElement position="3"> <pointcut>/aco:SubComponents/aco:AmaImageComponent[@id='aqwrz6if']/aco:MetaInformation/amet:ImageMetaData</pointcut> 
		<to>/aco:MetaInformation/amet:LayoutProperties/alay:LayoutManager/alay:BoxLayout</to> 
		</moveElement> <insertElement position="3"> <pointcut>/aco:Hyperlinks</pointcut> 
		<value> <elementTemplate> <aco:AmaComponentLinkComponent id="faskzafnsdf" 
		name="h2" layer="Hyperlink"> <aco:MetaInformation> <amet:LinkComponentMetaData> 
		<amet:linktype>Strukturlink</amet:linktype> </amet:LinkComponentMetaData> 
		</aco:MetaInformation> <aco:From component="w12345" /> <aco:To base="aspects.ama" 
		/> </aco:AmaComponentLinkComponent> </elementTemplate> </value> </insertElement> 
		<insertElement position="6"> <pointcut>/aco:MetaInformation/amet:LayoutProperties/alay:LayoutManager/alay:BoxLayout</pointcut> 
		<value> <elementTemplate> <alay:ComponentRef>w12345</alay:ComponentRef> </elementTemplate> 
		</value> </insertElement> <insertElement position="3"> <pointcut>/aco:SubComponents</pointcut> 
		<value> <elementTemplate> <aco:AmaImageComponent id="asduekhc" layer="Media" 
		name="w12345"> <aco:MetaInformation> <amet:ImageMetaData> <amet:source>images/home_en.png</amet:source> 
		<amet:alt>ällabätsch</amet:alt> </amet:ImageMetaData> </aco:MetaInformation> 
		</aco:AmaImageComponent> </elementTemplate> </value> </insertElement> </advices> 
		</adviceGroup -->
	<!--adviceGroup> <scope> <xpath>//aco:AmaSetComponent[@id='j91t3sk7']/aco:SubComponents/aco:AmaAccessElement</xpath> 
		<joinpoint locator="before" name="T_AspectWeaverS1" /> </scope> <advices> 
		<delete> <pointcut>/aco:Hyperlinks/aco:AmaComponentLinkComponent[./aco:From/@component='w12345']</pointcut> 
		</delete> <delete> <pointcut>/aco:MetaInformation/amet:LayoutProperties/alay:LayoutManager/alay:BoxLayout/alay:ComponentRef[text()='w12345']</pointcut> 
		</delete> <delete> <pointcut>/aco:SubComponents/aco:AmaImageComponent[@name='w12345']</pointcut> 
		</delete> </advices> </adviceGroup -->

	<adviceGroup>
		<scope>
			<xpath>//aco:AmaSetComponent[@id='j91t3sk7']/aco:SubComponents/aco:AmaAccessElement
			</xpath>
			<joinpoint locator="after" name="T_WebService" />
		</scope>
		<advices>
			<changeValue>
				<pointcut>/aco:SubComponents/aco:AmaImageComponent[@id='aqwrz6if']/aco:MetaInformation/amet:ImageMetaData/amet:source
				</pointcut>
				<value>
					<textTemplate>"images/homeL.png"</textTemplate>
				</value>
			</changeValue>
			<changeValue>
				<pointcut>/aco:SubComponents/aco:AmaImageComponent[@id='aqwrz6if']/aco:MetaInformation/amet:ImageMetaData/amet:source[text()='images/homeL.png']</pointcut>
				<value>
					<textTemplate>"stuff"</textTemplate>
				</value>
			</changeValue>
		</advices>
	</adviceGroup>

	<!--adviceGroup> <scope> <xpath>//aco:AmaSetComponent[@id='j91t3sk7']/aco:SubComponents/aco:AmaAccessElement</xpath> 
		<joinpoint locator="before" name="T_AspectWeaverS1" /> </scope> <advices> 
		<delete> <pointcut>/aco:SubComponents/aco:AmaImageComponent[@id='aqwrz6if']/aco:MetaInformation/amet:ImageMetaData/amet:source[@text='images/home.png']</pointcut> 
		</delete> </advices> </adviceGroup -->

	<!--adviceGroup> <scope> <xpath>/books:bookList</xpath> </scope> <advices> 
		<expandElement> <pointcut>books:book/books:title</pointcut> <value> <elementTemplate> 
		<img xmlns="http://books">{$joinPoint/text()}-cover.jpg</img> </elementTemplate> 
		</value> </expandElement> </advices> </adviceGroup -->


</aspect>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.integration.application/WebContent/resources/weavingOperationsTest/AspectDelete2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="aspectDelete"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://www.w3.org/1999/xhtml"/>
	</interface>
	<adviceGroup>
		<depends evaluationMode="sparql">
			<boolExpr>"${userMail}" = "mart.lehmann@t-online.de"</boolExpr>
			<sparql>SELECT ?userMail WHERE {&lt;http://mmt.inf.tu-dresden.de/crocoon/User#${sessionId}&gt; &lt;http://mmt.inf.tu-dresden.de/crocoon/context-person.owl#mail&gt; ?userMail . Filter (?userMail = 'Marie@gmail.de')}</sparql>
		</depends>
		<scope>
			<xpath>/</xpath>
			<joinpoint locator="before" name="PostProcessing"/>
		</scope>
		<advices>
			<delete>
				<pointcut>h:link[@id='loginButtonLink']</pointcut>
			</delete>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.test/testData/interactionDetectionTest/Translation.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="Translation"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface> 
		<core id="core" type="http://www.hyperadapt.net/amacont/2008/AmaComponent" />
		<contextParameters>
			<parameter>
				<name>language</name>
			</parameter>
		</contextParameters>
	</interface>
	<adviceGroup>
		<depends>
			<boolExpr>$language='EN'</boolExpr>
		</depends>
		<scope>
			<joinpoint locator="before" name="T_WebService"/>
		</scope>
		<advices>
			<changeValue>
				<pointcut>/aco:AmaWebPageComponent//*[@name='content_boxes']/aco:SubComponents/aco:AmaSetComponent/aco:SubComponents/aco:AmaListComponent//aco:AmaStructuredTextComponent/attribute::name|
						  /aco:AmaWebPageComponent//*[@name='introduction']|
						  /aco:AmaWebPageComponent//*[@name='disclaimer']|
						  /aco:AmaWebPageComponent//*[@name='navbar']//aco:AmaTextComponent|
						  /aco:AmaWebPageComponent//*[@name='metainfo']//aco:AmaStructuredTextComponent
				</pointcut>	
				<value>
					<textTemplate>concat($joinPoint,'_en')</textTemplate>
				</value>
			</changeValue>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/net.hyperadapt.pxweave.test/testData/weavingOperationsTest/AspectChangeOrder.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="aspectChangeOrder"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://books"/>
	</interface>
	<adviceGroup>
		<scope>
			<xpath>/books:bookList</xpath>
		</scope>
		<advices>
			<changeOrder>
				<pointcut>books:book[3]/books:author</pointcut>
				<permutation>(3 1 2)</permutation>
			</changeOrder>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/weavingOperationsTest/AspectDelete.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="aspectDelete"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://books" />
	</interface>
	<adviceGroup>
		<depends>
			<boolExpr>1+1=2</boolExpr>
		</depends>
		<scope>
			<xpath>/books:bookList</xpath>
		</scope>
		<advices>
			<delete>
				<pointcut>/books:book[position()>1]</pointcut>
			</delete>
		</advices>
	</adviceGroup>
</aspect>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/weavingOperationsTest/AspectChooseVariant.xml
<?xml version="1.0" encoding="UTF-8" ?>
<aspect name="chooseVariant"
	xsi:schemaLocation="http://www.hyperadapt.net/pxweave/aspects ../../../net.hyperadapt.pxweave/schemas/aspectE2.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hyperadapt.net/pxweave/aspects">
	<interface>
		<core id="core" type="http://books" />
	</interface>
	<adviceGroup>
		<scope>
			<xpath>/books:bookList</xpath>
		</scope>
		<advices>
			<chooseVariant>
				<pointcut>/books:book[1]</pointcut>
			</chooseVariant>
		</advices>
	</adviceGroup>
</aspect>
