=== javafrog/hyperadapt/net.hyperadapt.pxweave.test/testData/music.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://music"
	targetNamespace="http://music" elementFormDefault="qualified">

	<xsd:element name="music-database">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="album" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="album">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="title" />
				<xsd:choice>
					<xsd:element ref="artist" />
					<xsd:element ref="compilation" />
				</xsd:choice>
				<xsd:element ref="id" />
				<xsd:element minOccurs="0" name="edition" type="Edition" />
				<xsd:element ref="publisher" />
				<xsd:element minOccurs="0" ref="year" />
				<xsd:element minOccurs="0" ref="image"/>
				<xsd:element minOccurs="0" ref="media" />
			</xsd:sequence>
			<xsd:attribute name="price" type="xsd:decimal" />
			<xsd:attribute name="inStock" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Yes" />
						<xsd:enumeration value="No" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="title" type="xsd:string" />

	<xsd:element name="artist">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element name="pseudonym" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="image">
		<xsd:complexType>
			<xsd:attribute name="url" type="xsd:string"/>
				<xsd:attribute name="size" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="SMALL" />
						<xsd:enumeration value="LARGE" />
						<xsd:enumeration value="TINY" />
						<xsd:enumeration value="THUMBNAIL" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="media">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="1" ref="medium" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
		<xsd:element name="medium">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="1" ref="tracks" />
			</xsd:sequence>
			<xsd:attribute name="kind" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="CD" />
						<xsd:enumeration value="DVD" />
						<xsd:enumeration value="MD" />
						<xsd:enumeration value="LP" />
						<xsd:enumeration value="MP3" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="tracks">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="1" maxOccurs="unbounded" ref="song" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="song">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" maxOccurs="1" ref="artist" />
			</xsd:sequence>
			<xsd:attribute name="length" type="xsd:decimal" />
			<xsd:attribute name="name" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="id" type="xsd:string" />

	<xsd:element name="publisher" type="xsd:string" />
	<xsd:element name="compilation" type="xsd:string" />
	<xsd:element name="year">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9]{4}" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:simpleType name="Edition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="First" />
			<xsd:enumeration value="Second" />
			<xsd:enumeration value="Third" />
			<xsd:enumeration value="Fourth" />
			<xsd:enumeration value="Fifth" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.test/testData/result.xml
<?xml version="1.0" encoding="UTF-8"?><music-database xmlns="http://music" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://music music.xsd">
	<album inStock="Yes">
		<title>How to Be a Megastar-Live!</title>
		<artist>
			<pseudonym>Blue Man Group</pseudonym>
		</artist>
		<id>B00166GLVO</id>
		<edition>First</edition>
		<publisher>Rhino (Warner)</publisher>
		<image size="SMALL" url="http://www.amazon.de/gp/product/images/B001S1ZBC2/ref=dp_image_0?ie=UTF8&amp;n=77195031&amp;s=dmusic"/>
			
			
		<media>
			<medium kind="CD">
				<tracks>
					<song length="3.30" name="Above"/>
					<song length="3.25" name="Drumbone"/>
					<song length="4.22" name="Time To Start"/>
					<song length="4.16" name="Up To The Roof"/>
					<song length="2.23" name="Altering Appearances"/>
					<song length="4.12" name="Persona"/>
					<song length="4.04" name="Your Attention"/>
					<song length="6.01" name="Piano Smasher "/>
					<song length="4.40" name="Shirts And Hats"/>
					<song length="3.10" name="Sing Along"/>
				</tracks>
			</medium>
		</media>
	</album>
</music-database>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/testData/music_db.xml
<?xml version="1.0"?>
<music-database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://music music.xsd" xmlns="http://music">
	<album inStock="Yes">
		<title>How to Be a Megastar-Live!</title>
		<artist>
			<pseudonym>Blue Man Group</pseudonym>
		</artist>
		<id>B00166GLVO</id>
		<edition>First</edition>
		<publisher>Rhino (Warner)</publisher>
		<image size="SMALL" url="http://www.amazon.de/gp/product/images/B001S1ZBC2/ref=dp_image_0?ie=UTF8&amp;n=77195031&amp;s=dmusic"/>
		<image size="LARGE" url="http://ecx.images-amazon.com/images/I/51jalkEVvCL._SS500_.jpg"/>	
		<image size="TINY" url="http://ecx.images-amazon.com/images/I/51jalkEVvCL._SS500_tiny.jpg"/>	
		<media>
			<medium kind="CD">
				<tracks>
					<song name="Above" length="3.30" />
					<song name="Drumbone" length="3.25" />
					<song name="Time To Start" length="4.22" />
					<song name="Up To The Roof" length="4.16" />
					<song name="Altering Appearances" length="2.23" />
					<song name="Persona" length="4.12" />
					<song name="Your Attention" length="4.04" />
					<song name="Piano Smasher " length="6.01" />
					<song name="Shirts And Hats" length="4.40" />
					<song name="Sing Along" length="3.10" />
				</tracks>
			</medium>
		</media>
	</album>
</music-database>
