=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/examples/catalogSalamiSlice.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="journal" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="title" type="xs:string"/>
            <xs:attribute name="publisher" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="journal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="article" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="date" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="article">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="author"/>
                <xs:element ref="text"/>
                <xs:element ref="imageVariants" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="section">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Features"/>
                        <xs:enumeration value="SQL"/>
                        <xs:enumeration value="PL/SQL"/>
                        <xs:enumeration value="JSP"/>
                        <xs:enumeration value="XML"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="text">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="textFrame" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="textFrame">
        <xs:complexType mixed="true">
            <xs:attribute name="number" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="imageVariants">
        <xs:complexType mixed="true">
            <xs:choice>
                <xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="imageDescription" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="height"/>
                <xs:element ref="width"/>
                <xs:element ref="url"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="height" type="xs:integer"/>
    <xs:element name="width" type="xs:integer"/>
    <xs:element name="url" type="xs:string"/>
    <xs:element name="imageDescription" type="xs:string"/>
</xs:schema>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.test/examples/result2.xml
<?xml version="1.0" encoding="utf-8"?><catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" publisher="Oracle Publishing" title="Oracle Magazine" xsi:noNamespaceSchemaLocation="catalogSalamiSlice.xsd">


	<journal date="November-December 2003">
		
		
		<article section="JSP">
			<title>Servlets and JSP Step Up</title>
			<author>Budi Kurniawan</author>
			<text><textFrame number="1">Article coming soon</textFrame>
			</text><imageVariants>
				<image>
					<height>120</height>
					<width>200</width>
					<url>mainPage/img_small.jpg</url>
				</image>
				<image>
					<height>180</height>
					<width>300</width>
					<url>mainPage/img_medium.jpg</url>
				</image>
				<image>
					<height>240</height>
					<width>400</width>
					<url>mainPage/img_large.jpg</url>
				</image>
			</imageVariants>
		</article>
		<article>
		<title>someTitle</title>	
		<author>unknown</author>
		<text>
			<textFrame number="0"/>
			<textFrame number="1"/>
			<textFrame number="2"/>		
		</text>	
		</article>
	</journal>
</catalog>

=== javafrog/hyperadapt/branches/pxweave4jsf/net.hyperadapt.pxweave.test/examples/catalogResult.xml
<?xml version="1.0" encoding="utf-8"?><catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogSalamiSlice.xsd" title="Oracle Magazine" publisher="Oracle Publishing">


	<journal date="November-December 2003">
		
		<article section="XML">
			<title>Dom+Xquery</title>
			<author>Jason Hunter</author>
			<text><textFrame number="0">cellPhone</textFrame><textFrame number="1">DOM parsing creates an in-memory tree that mirrors the structure of  the parsed
						XML document. Subsequently, you can navigate the tree using the DOM
						API. In this  case, you'll see how to iterate over the parsed XML document
						and output element and  attribute node values. 
				</textFrame><textFrame number="2">You can obtain an element's text by first  retrieving the text node from the
						element node and then requesting the value of the text node.
				</textFrame><textFrame number="3">...and do fancy stuff with it.
				</textFrame><textFrame number="4">The DOM parsing API classes
						are in the oracle.xml.parser.v2 package  and the DOM parser factory
						and parser classes are in the oracle.xml.jaxp package.
				</textFrame><textFrame number="5">JSP</textFrame></text>
		</article>
		<article section="JSP">
			<title>Servlets and JSP Step Up</title>
			<author>Budi Kurniawan</author>
			<text><textFrame number="0">cellPhone</textFrame><textFrame number="1">Article coming soon</textFrame></text><imageVariants>someTextReplacingTheImages</imageVariants>
		</article>
		<article>
		<title>someTitle</title>	
		<author>unknown</author>
		<text><textFrame number="0">cellPhonetextAgaintextAgaintextAgaintextAgaintextAgain</textFrame><textFrame number="0">textAgaintextAgaintextAgaintextAgaintextAgain</textFrame><textFrame number="1">someTextsomeTextsomeTextsomeTextsomeTextsomeTextsomeTextsomeTextsomeTextsomeTextsomeText</textFrame><textFrame number="2">textText  textText  textText  textText  textText  textText  textText  </textFrame></text>	
		</article>
	</journal>
</catalog>
