=== javafrog/hyperadapt/net.hyperadapt.pxweave.interactions.plugin/PatternConflicts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
    <xsd:element name="PatternConflicts">
        <xsd:complexType>
            <xsd:all>
                <xsd:element minOccurs="0" maxOccurs="1" name="ChangeOrder" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="ChangeValue" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="ChooseVariant" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="CollapseElement" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="DeleteElement" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="EnrichContent" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="ExpandElement" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="MoveElement" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="ReduceContent" type="AllSecondPatterns"/>
                <xsd:element minOccurs="0" maxOccurs="1" name="InsertElement" type="AllSecondPatterns"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="AllSecondPatterns">
        <xsd:all>
            <xsd:element minOccurs="0" maxOccurs="1" name="ChangeOrder" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="ChangeValue" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="ChooseVariant" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="CollapseElement" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="DeleteElement" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="ExpandElement" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="EnrichContent" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="MoveElement" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="ReduceContent" type="SecondPattern"/>
            <xsd:element minOccurs="0" maxOccurs="1" name="InsertElement" type="SecondPattern"/>
        </xsd:all>    
    </xsd:complexType>
    <xsd:complexType name="SecondPattern">
        <xsd:sequence>
            <xsd:element name="status" type="status"/>
            <xsd:element name="reason" type="xsd:string"/>
            <xsd:element name="solution" type="xsd:string" default="no solution yet"/>
        </xsd:sequence>    
    </xsd:complexType>
    <xsd:simpleType name="status">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="warning"/>
            <xsd:enumeration value="error"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== javafrog/hyperadapt/trunk/net.hyperadapt.pxweave.interactions.plugin/PatternConflicts.xml
<?xml version="1.0" encoding="UTF-8"?>
<PatternConflicts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="PatternConflicts.xsd">
	<ChangeOrder>
		<ChangeOrder>
			<status>warning</status>
			<reason>ChangeOrder -> ChangeOrder</reason>
			<solution>no solution yet</solution>
		</ChangeOrder>
		<ChooseVariant>
			<status>warning</status>
			<reason>ChangeOrder -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>ChangeOrder -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>ChangeOrder -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
	</ChangeOrder>
	<ChangeValue>
		<ChangeOrder>
			<status>warning</status>
			<reason>ChangeValue -> ChangeOrder</reason>
			<solution>no solution yet</solution>
		</ChangeOrder>
		<ChangeValue>
			<status>warning</status>
			<reason>ChangeValue -> ChangeValue</reason>
			<solution>no solution yet</solution>
		</ChangeValue>
		<ChooseVariant>
			<status>warning</status>
			<reason>ChangeValue -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>ChangeValue -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>warning</status>
			<reason>ChangeValue -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<EnrichContent>
			<status>warning</status>
			<reason>ChangeValue -> EnrichContent</reason>
			<solution>no solution yet</solution>
		</EnrichContent>
		<ExpandElement>
			<status>warning</status>
			<reason>ChangeValue -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<InsertElement>
			<status>warning</status>
			<reason>ChangeValue -> InsertElement</reason>
			<solution>no solution yet</solution>
		</InsertElement>
		<MoveElement>
			<status>warning</status>
			<reason>ChangeValue -> MoveElement</reason>
			<solution>no solution yet</solution>
		</MoveElement>
		<ReduceContent>
			<status>warning</status>
			<reason>ChangeValue -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</ChangeValue>
	<ChooseVariant>
		<ChooseVariant>
			<status>warning</status>
			<reason>ChooseVariant -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>ChooseVariant -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>ChooseVariant -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<ExpandElement>
			<status>error</status>
			<reason>ChooseVariant -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<ReduceContent>
			<status>error</status>
			<reason>ChooseVariant -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</ChooseVariant>
	<CollapseElement>
		<ChangeOrder>
			<status>error</status>
			<reason>CollapseElement -> ChangeOrder</reason>
			<solution>no solution yet</solution>
		</ChangeOrder>
		<ChooseVariant>
			<status>warning</status>
			<reason>CollapseElement -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>error</status>
			<reason>CollapseElement -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>CollapseElement -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<ExpandElement>
			<status>warning</status>
			<reason>CollapseElement -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<ReduceContent>
			<status>warning</status>
			<reason>CollapseElement -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</CollapseElement>
	<DeleteElement>
		<ChangeOrder>
			<status>error</status>
			<reason>DeleteElement -> ChangeOrder</reason>
			<solution>no solution yet</solution>
		</ChangeOrder>
		<ChangeValue>
			<status>error</status>
			<reason>DeleteElement -> ChangeValue</reason>
			<solution>no solution yet</solution>
		</ChangeValue>
		<ChooseVariant>
			<status>error</status>
			<reason>DeleteElement -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>error</status>
			<reason>DeleteElement -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>DeleteElement -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<EnrichContent>
			<status>error</status>
			<reason>DeleteElement -> EnrichContent</reason>
			<solution>no solution yet</solution>
		</EnrichContent>
		<ExpandElement>
			<status>error</status>
			<reason>DeleteElement -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<InsertElement>
			<status>error</status>
			<reason>DeleteElement -> InsertElement</reason>
			<solution>no solution yet</solution>
		</InsertElement>
		<MoveElement>
			<status>error</status>
			<reason>DeleteElement -> MoveElement</reason>
			<solution>no solution yet</solution>
		</MoveElement>
		<ReduceContent>
			<status>error</status>
			<reason>DeleteElement -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</DeleteElement>
	<EnrichContent>
		<ChooseVariant>
			<status>warning</status>
			<reason>EnrichContent -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>EnrichContent -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>EnrichContent -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<ReduceContent>
			<status>warning</status>
			<reason>EnrichContent -> ReduceCOntent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</EnrichContent>
	<ExpandElement>
		<ChooseVariant>
			<status>warning</status>
			<reason>ExpandElement -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>ExpandElement -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>ExpandElement -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<ExpandElement>
			<status>error</status>
			<reason>ExpandElement -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<ReduceContent>
			<status>error</status>
			<reason>ExpandElement -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</ExpandElement>
	<MoveElement>
		<ChangeOrder>
			<status>error</status>
			<reason>MoveElement -> ChangeOrder</reason>
			<solution>no solution yet</solution>
		</ChangeOrder>
		<ChangeValue>
			<status>error</status>
			<reason>MoveElement -> ChangeValue</reason>
			<solution>no solution yet</solution>
		</ChangeValue>
		<ChooseVariant>
			<status>error</status>
			<reason>MoveElement -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>error</status>
			<reason>MoveElement -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>MoveElement -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<EnrichContent>
			<status>error</status>
			<reason>MoveElement -> EnrichContent</reason>
			<solution>no solution yet</solution>
		</EnrichContent>
		<ExpandElement>
			<status>error</status>
			<reason>MoveElement -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<InsertElement>
			<status>error</status>
			<reason>MoveElement -> InsertElement</reason>
			<solution>no solution yet</solution>
		</InsertElement>
		<MoveElement>
			<status>error</status>
			<reason>MoveElement -> MoveElement</reason>
			<solution>no solution yet</solution>
		</MoveElement>
		<ReduceContent>
			<status>error</status>
			<reason>MoveElement -> ReduceContent</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</MoveElement>
	<ReduceContent>
		<ChooseVariant>
			<status>warning</status>
			<reason>ReduceContent -> ChooseVariant</reason>
			<solution>no solution yet</solution>
		</ChooseVariant>
		<CollapseElement>
			<status>warning</status>
			<reason>ReduceContent -> CollapseElement</reason>
			<solution>no solution yet</solution>
		</CollapseElement>
		<DeleteElement>
			<status>error</status>
			<reason>ReduceContent -> DeleteElement</reason>
			<solution>no solution yet</solution>
		</DeleteElement>
		<EnrichContent>
			<status>warning</status>
			<reason>ReduceContent -> EnrichContent</reason>
			<solution>no solution yet</solution>
		</EnrichContent>
		<ExpandElement>
			<status>warning</status>
			<reason>ReduceContent -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ExpandElement>
		<ReduceContent>
			<status>warning</status>
			<reason>ReduceContent -> ExpandElement</reason>
			<solution>no solution yet</solution>
		</ReduceContent>
	</ReduceContent>
</PatternConflicts>
